Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NewCore3xMVC.Models;
using System.Text.Json;

namespace NewCore3xMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Tutorials()
        {
            return View();
        }

        public IActionResult Middleware()
        {
            return View();
        }

        public IActionResult TagHelper()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Principal;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using NewCore3xMVC.Data;
using NewCore3xMVC.Models;
using NewCore3xMVC.Models.Views;
using Newtonsoft.Json;

namespace NewCore3xMVC.Controllers
{
    public class PeopleController : Controller
    {
        private readonly NewCore3xMVCContext _context;
        private IMemoryCache _memoryCache;
        private IDistributedCache _distributedCache;

        public PeopleController(NewCore3xMVCContext context, IMemoryCache memoryCache, IDistributedCache distributedCache)
        {
            _memoryCache = memoryCache;
            _distributedCache = distributedCache;
            _context = context;

        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.Person.Include(d => d.Address).ToListAsync());
        }

        public IActionResult RawQuery(int id)
        {
            var sql = "SELECT * FROM People WHERE AutoID = {0}";

            var data = _context.Person.FromSqlRaw(sql, id).FirstOrDefault();

            return View(data);
        }


        public IActionResult RawQueryComplex(int id)
        {
            IList<PersonAddressView> list = new List<PersonAddressView>();
            using (var conn = _context.Database.GetDbConnection())
            {
                conn.Open();
                using (var command = conn.CreateCommand())
                {
                    var sql = "SELECT P.AutoId, P.FirstName, P.LastName, P.Age, P.Active, P.AddressId, A.AddressLine, A.City, A.Pin FROM People P, Addresses A " +
                        " WHERE P.AddressId = A.AddressId";
                    command.CommandText = sql;
                    using(var reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                var record = new PersonAddressView()
                                {
                                    Active = reader.GetBoolean(4),
                                    AddressId = reader.GetInt32(5),
                                    AddressLine = reader.GetString(6),
                                    Age = reader.GetInt32(3),
                                    AutoId = reader.GetInt32(0),
                                    City = reader.GetString(7),
                                    FirstName = reader.GetString(1),
                                    LastName = reader.GetString(2),
                                    Pin = reader.GetString(8)
                                };
                                list.Add(record);
                            }
                        }
                    } // reader
                } // command
                conn.Close();
            } // connection

            return View(list);
        }
      

        #region InMemory Caching options

        public async Task<IActionResult> CacheIndex()
        {
            var cacheData = _memoryCache.Get("PeopleData");

            IList<Person> data = new List<Person>();

            if (cacheData == null)
            {
                data = await _context.Person.ToListAsync();

                var cacheOptions = new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromSeconds(60));

                _memoryCache.Set("PeopleData", data, cacheOptions);
            }
            else
            {
                data = (IList<Person>)cacheData;
            }
            return View(data);
        }

        public IActionResult RemoveCache()
        {
            _memoryCache.Remove("PeopleData");

            return RedirectToAction("CacheIndex");
        }

        #endregion InMemory Caching options

        #region Distributed Cache

        public async Task<IActionResult> RedisCache()
        {
            IList<Person> data = new List<Person>();

            var isCacheString = _distributedCache.GetString("RedisData");
            if (string.IsNullOrEmpty(isCacheString))
            {
                data = await _context.Person.ToListAsync();

                // convert collection into serialized string
                var dataString = JsonConvert.SerializeObject(data);

                var distributedCacheOptions = new DistributedCacheEntryOptions();
                distributedCacheOptions.SetSlidingExpiration(TimeSpan.FromSeconds(5000));

                await _distributedCache.SetStringAsync("RedisData", dataString, distributedCacheOptions);
            }
            else
            {


                data = JsonConvert.DeserializeObject<IList<Person>>(isCacheString);
            }

            return View(data);
        }

        public IActionResult RemoveRedisCache()
        {
            _distributedCache.Remove("RedisData");

            return RedirectToAction("RedisCache");
        }



        #endregion

        #region Response Caching Options
        // TRY uncommenting ResponseCache related code from ConfigureService and Configure method from Startup.cs and 
        // run RemoveRedisCache method and you won't see data getting removed or break point hitting.

        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [ResponseCache(Duration = 30000)]
        public async Task<IActionResult> ResponseCaching()
        {
            return View("Index", await _context.Person.ToListAsync());
        }

        #endregion Response Caching Options



        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.AutoId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AutoId,FirstName,LastName,Age,Active")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutoId,FirstName,LastName,Age,Active")] Person person)
        {
            if (id != person.AutoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.AutoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        public async Task<ActionResult> Search()
        {
            return View(new List<Person>());
        }

        [HttpPost]
        public async Task<ActionResult> Search(IFormCollection form)
        {
            var keyword = form["keyword"];
            var data = await _context.Person.Where(d => d.FirstName.Contains(keyword) || d.LastName.Contains(keyword)).ToListAsync();
            ViewBag.Keyword = keyword;
            return View(data);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.AutoId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Person.FindAsync(id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Controllers/RepositoryTestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RepositoryPattern;
using RepositoryPattern.Models;

namespace NewCore3xMVC.Controllers
{
    public class RepositoryTestsController : Controller
    {
        private IRepositoryWrapper _repositoryWrapper;

        public RepositoryTestsController(IRepositoryWrapper repositoryWrapper)
        {
            _repositoryWrapper = repositoryWrapper;
        }

        public IActionResult Index()
        {
            var people = _repositoryWrapper.People.FindAll();
            return View(people);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AutoId,FirstName,LastName,Age,Active")] People people)
        {
            if (ModelState.IsValid)
            {
                _repositoryWrapper.People.Create(people);
                _repositoryWrapper.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }


        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = _repositoryWrapper.People.FindByCondition(d => d.AutoId == id.Value).FirstOrDefault();
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutoId,FirstName,LastName,Age,Active")] People people)
        {
            if (id != people.AutoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repositoryWrapper.People.Update(people);


                    // find the employee records and try to update both people and employee records at a time using RepositoryPattern
                    var employee = _repositoryWrapper.Employees.FindByCondition(d => d.ID == id).FirstOrDefault();
                    if (employee != null)
                    {
                        employee.FileName = people.FirstName + "_" + people.LastName + ".jpg";
                        _repositoryWrapper.Employees.Update(employee);
                    }

                    _repositoryWrapper.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(people.AutoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = _repositoryWrapper.People.FindByCondition(m => m.AutoId == id).FirstOrDefault();
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = _repositoryWrapper.People.FindByCondition(d => d.AutoId == id).FirstOrDefault();
            _repositoryWrapper.People.Delete(person);
            _repositoryWrapper.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _repositoryWrapper.People.FindByCondition(e => e.AutoId == id).FirstOrDefault() == null;
        }
    }
}

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Views/Home/Middleware.cshtml
@{
    ViewData["Title"] = "Middleware";
}

<div class="card card-body bg-info">Check Startup.cs</div>

<h1>Middleware</h1>

Middleware is a logic/code that can be injected in the request-response pipeline of .net core application.

<p>
    The HTTP requests are managed by Request Delegates in the pipeline that can be configured using following extension methods.
</p>
<ol>
    <li><b>Use</b> This is used to register the middleware logic and pass the request to the next middleware in the pipeline.</li>
    <li><b>Map</b> It is used to map the requested url to specific action</li>
    <li><b>Run</b> It is used to end the register the middleware logic and end the pipeline registration. If you put any other middlewar after this, it doesn't execute.</li>
</ol>
Middleware is registered in the Startup.cs -> Configure mehtod.

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Views/Home/TagHelper.cshtml
@{
    ViewData["Title"] = "TagHelper";
}

<h1>TagHelper</h1>


<p class="card card-body bg-secondary">
    Attribute that starts with asp- is part of tag helper methods. Its available with almost all html tags.
</p>
@("The multiplication is :" + new NewCore3xMVC.Utility.Utility().Multiply(2,3,5,9,8))
<hr />
@("The sum is " + NewCore3xMVC.Utility.Utility.Sum(2, 3, 4, 5))
<hr />
@{ PrintTable(10); }
<hr />
The sum of 2, 4 is <strong>@Sum(2, 4)</strong>.
@{
    void PrintTable(int number)
    {
        <ul>
            @for (var i = 1; i < 11; i++)
            {
                <li>@(i*number)</li>
            }
        </ul>
    }
}

@functions
{
    public int Sum(int a, int b)
    {
        return a + b;
    }
}

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Views/Home/Tutorials.cshtml
@{
    ViewData["Title"] = "Tutorials";
}

<h1>Tutorials</h1>
<div class="row">
    <div class="col-md-6">
        <ol>
            <li><a asp-action="CacheIndex" asp-controller="People" target="_blank">Cache Index</a></li>
            <li><a asp-action="ResponseCaching" asp-controller="People" target="_blank">Response Caching</a></li>
            <li><a asp-action="RedisCache" asp-controller="People" target="_blank">Redis Caching</a></li>
            <li><a asp-action="Index" asp-controller="RepositoryTests" target="_blank">Repository Pattern</a></li>
        </ol>
        <h4>Routing</h4>
        <ol>
            <li><a href="/Hello" target="_blank">Content routing</a></li>
            <li><a href="/Default/2/sheo" target="_blank">Constraint routing</a></li>
            <li><a href="/Privacy" target="_blank">Privacy</a></li>
        </ol>

        <h4>Middleware</h4>
        <ol>
            <li><a href="/Home/Middleware" target="_blank">Middleware</a></li>
        </ol>

        <h4>Dependency Injection</h4>
        <ol>
            <li><a href="/DI/Index" target="_blank">Inject Custom Service</a></li>
        </ol>

        <h4>Paging</h4>
        <ol>
            <li><a href="/Employees/Paging" target="_blank">Pagination</a></li>
            <li><a href="/Employees/Search" target="_blank">Search</a></li>
        </ol>
    </div>
    <div class="col-md-6">
        <h4>Raw SQL</h4>
        <ol>
            <li><a href="/People/RawQuery/1" target="_blank">Raw Query</a></li>
            <li><a href="/People/RawQueryComplex" target="_blank">Raw Complex Query</a></li>
        </ol>
        <h4>Partial Views</h4>
        <ol>
            <li><a href="/Default/PartialViewTest" target="_blank">Partial View Test</a></li>
        </ol>
        <h4>Components</h4>
        <ol>
            <li><a href="/Default/ComponentTest" target="_blank">Component Test</a></li>
        </ol>
        <h4>Error Handling</h4>
        <ol>
            <li><a href="/ErrorHandling">Error Handling</a></li>
        </ol>
        <h4>Logging</h4>
        <ol>
            <li><a href="/Logging">Logging</a></li>
        </ol>        <h4>Tag Helper / Functions</h4>
        <ol>
            <li><a href="/Home/TagHelper">TagHelper</a></li>
        </ol>

        <h4>Result Types</h4>
        <ul>
            <li><a href="/ResultTypes">Result Types</a></li>
        </ul>

        <h4>Cookie / Session</h4>
        <ul>
            <li><a href="/SessionDemo">Cookie / Session</a></li>
        </ul>
        <h4>ViewBag / ViewData</h4>
        <ul>
            <li><a href="/ViewBagViewData">View Bag, View Data</a></li>
        </ul>

    </div>
</div>

Nikhil/Nikhil/TRAINEERDOC/SHEO/NewCore3xMVC/NewCore3xMVC/Views/Home/_HomePartial.cshtml
<div class="card card-body bg-secondary">
    <p>
        Partial View from <b>Home folder</b>: Today is @DateTime.Now.ToLongDateString()
    </p>
</div>